name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

  runs-on: ubuntu-latest

  strategy:
    matrix:
      node-version: [14.x, 16.x, 18.x]
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  steps:
  - uses: actions/checkout@v3
  - name: Use beautybar ${{ matrix.node-version }}
    uses: actions/setup-node@v3
    with:
      node-version: ${{ matrix.node-version }}
      cache: 'npm'
  - run: npm ci
  - run: npm run build --if-present
  - run: npm test --if-present
  env:
  HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}
  - run: heroku container:login
  - name: Build and push
  env:
  HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}
  run: heroku container:push -a beauty-bar web
  - name: Release
  env:
  HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}
  run: heroku container:release -a beauty-bar web
